export const SEARCH_BUILDING_REQUEST = "SEARCH_BUILDING_REQUEST";
export const SEARCH_BUILDING_SUCCESS = "SEARCH_BUILDING_SUCCESS";
export const SEARCH_BUILDING_FAILURE = "SEARCH_BUILDING_FAILURE";

export const GET_BUILDING_REQUEST = "GET_BUILDING_REQUEST";
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS";
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE";

export const GET_BUILDING_ENABLE_REQUEST = "GET_BUILDING_ENABLE_REQUEST";
export const GET_BUILDING_ENABLE_SUCCESS = "GET_BUILDING_ENABLE_SUCCESS";
export const GET_BUILDING_ENABLE_FAILURE = "GET_BUILDING_ENABLE_FAILURE";

export const ADD_BUILDING_REQUEST = "ADD_BUILDING_REQUEST";
export const ADD_BUILDING_SUCCESS = "ADD_BUILDING_SUCCESS";
export const ADD_BUILDING_FAILURE = "ADD_BUILDING_FAILURE";

export const UPDATE_BUILDING_REQUEST = "UPDATE_BUILDING_REQUEST";
export const UPDATE_BUILDING_SUCCESS = "UPDATE_BUILDING_SUCCESS";
export const UPDATE_BUILDING_FAILURE = "UPDATE_BUILDING_FAILURE";

export const DELETE_BUILDING_REQUEST = "DELETE_BUILDING_REQUEST";
export const DELETE_BUILDING_SUCCESS = "DELETE_BUILDING_SUCCESS";
export const DELETE_BUILDING_FAILURE = "DELETE_BUILDING_FAILURE";

export const DELETE_MULTIPLE_BUILDING_REQUEST =
  "DELETE_MULTIPLE_BUILDING_REQUEST";
export const DELETE_MULTIPLE_BUILDING_SUCCESS =
  "DELETE_MULTIPLE_BUILDING_SUCCESS";
export const DELETE_MULTIPLE_BUILDING_FAILURE =
  "DELETE_MULTIPLE_BUILDING_FAILURE";
