export const GET_DOT_MAP_REQUEST = "GET_DOT_MAP_REQUEST";
export const GET_DOT_MAP_SUCCESS = "GET_DOT_MAP_SUCCESS";
export const GET_DOT_MAP_FAILURE = "GET_DOT_MAP_FAILURE";

export const UPDATE_DOT_MAP_REQUEST = "UPDATE_DOT_MAP_REQUEST";
export const UPDATE_DOT_MAP_SUCCESS = "UPDATE_DOT_MAP_SUCCESS";
export const UPDATE_DOT_MAP_FAILURE = "UPDATE_DOT_MAP_FAILURE";

export const GET_DOT_LIST_REQUEST = "GET_DOT_LIST_REQUEST";
export const GET_DOT_LIST_SUCCESS = "GET_DOT_LIST_SUCCESS";
export const GET_DOT_LIST_FAILURE = "GET_DOT_LIST_FAILURE";

export const DELETE_DOT_LIST_REQUEST = "DELETE_DOT_LIST_REQUEST";
export const DELETE_DOT_LIST_SUCCESS = "DELETE_DOT_LIST_SUCCESS";
export const DELETE_DOT_LIST_FAILURE = "DELETE_DOT_LIST_FAILURE";

export const UPDATE_DOT_LIST_REQUEST = "UPDATE_DOT_LIST_REQUEST";
export const UPDATE_DOT_LIST_SUCCESS = "UPDATE_DOT_LIST_SUCCESS";
export const UPDATE_DOT_LIST_FAILURE = "UPDATE_DOT_LIST_FAILURE";

export const SEARCH_DOT_REQUEST = "SEARCH_DOT_REQUEST";
export const SEARCH_DOT_SUCCESS = "SEARCH_DOT_SUCCESS";
export const SEARCH_DOT_FAILURE = "SEARCH_DOT_FAILURE";

export const SWAP_DOT_REQUEST = "SWAP_DOT_REQUEST";
export const SWAP_DOT_SUCCESS = "SWAP_DOT_SUCCESS";
export const SWAP_DOT_FAILURE = "SWAP_DOT_FAILURE";

export const ACTIVE_DOT_REQUEST = "ACTIVE_DOT_REQUEST";
export const ACTIVE_DOT_SUCCESS = "ACTIVE_DOT_SUCCESS";
export const ACTIVE_DOT_FAILURE = "ACTIVE_DOT_FAILURE";

export const GET_DOT_REPORT_REQUEST = "GET_DOT_REPORT_REQUEST";
export const GET_DOT_REPORT_SUCCESS = "GET_DOT_REPORT_SUCCESS";
export const GET_DOT_REPORT_FAILURE = "GET_DOT_REPORT_FAILURE";

export const EXPORT_DOT_REQUEST = "EXPORT_DOT_REQUEST";
export const EXPORT_DOT_SUCCESS = "EXPORT_DOT_SUCCESS";
export const EXPORT_DOT_FAILURE = "EXPORT_DOT_FAILURE";
