export const SEARCH_FLOOR_REQUEST = "SEARCH_FLOOR_REQUEST";
export const SEARCH_FLOOR_SUCCESS = "SEARCH_FLOOR_SUCCESS";
export const SEARCH_FLOOR_FAILURE = "SEARCH_FLOOR_FAILURE";

export const GET_FLOOR_REQUEST = "GET_FLOOR_REQUEST";
export const GET_FLOOR_SUCCESS = "GET_FLOOR_SUCCESS";
export const GET_FLOOR_FAILURE = "GET_FLOOR_FAILURE";

export const GET_FLOOR_ENABLE_BY_BUILDING_ID_REQUEST =
  "GET_FLOOR_ENABLE_BY_BUILDING_ID_REQUEST";
export const GET_FLOOR_ENABLE_BY_BUILDING_ID_SUCCESS =
  "GET_FLOOR_ENABLE_BY_BUILDING_ID_SUCCESS";
export const GET_FLOOR_ENABLE_BY_BUILDING_ID_FAILURE =
  "GET_FLOOR_ENABLE_BY_BUILDING_ID_FAILURE";

export const ADD_FLOOR_REQUEST = "ADD_FLOOR_REQUEST";
export const ADD_FLOOR_SUCCESS = "ADD_FLOOR_SUCCESS";
export const ADD_FLOOR_FAILURE = "ADD_FLOOR_FAILURE";

export const UPDATE_FLOOR_REQUEST = "UPDATE_FLOOR_REQUEST";
export const UPDATE_FLOOR_SUCCESS = "UPDATE_FLOOR_SUCCESS";
export const UPDATE_FLOOR_FAILURE = "UPDATE_FLOOR_FAILURE";

export const UPDATE_ENABLE_FLOOR_REQUEST = "UPDATE_ENABLE_FLOOR_REQUEST";
export const UPDATE_ENABLE_FLOOR_SUCCESS = "UPDATE_ENABLE_FLOOR_SUCCESS";
export const UPDATE_ENABLE_FLOOR_FAILURE = "UPDATE_ENABLE_FLOOR_FAILURE";

export const DELETE_FLOOR_REQUEST = "DELETE_FLOOR_REQUEST";
export const DELETE_FLOOR_SUCCESS = "DELETE_FLOOR_SUCCESS";
export const DELETE_FLOOR_FAILURE = "DELETE_FLOOR_FAILURE";

export const DELETE_MULTIPLE_FLOOR_REQUEST = "DELETE_MULTIPLE_FLOOR_REQUEST";
export const DELETE_MULTIPLE_FLOOR_SUCCESS = "DELETE_MULTIPLE_FLOOR_SUCCESS";
export const DELETE_MULTIPLE_FLOOR_FAILURE = "DELETE_MULTIPLE_FLOOR_FAILURE";
