export const GET_GROUP_DEPARTMENT_REQUEST = "GET_GROUP_DEPARTMENT_REQUEST";
export const GET_GROUP_DEPARTMENT_SUCCESS = "GET_GROUP_DEPARTMENT_SUCCESS";
export const GET_GROUP_DEPARTMENT_FAILURE = "GET_GROUP_DEPARTMENT_FAILURE";

export const RESET_GROUP_DEPARTMENT = "RESET_GROUP_DEPARTMENT";
